/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AajpRouteImport } from './routes/aajp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as MapRouteImport } from './routes/map'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as ProfileRouteImport } from './routes/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AajpRoute = AajpRouteImport.update({
  id: '/aajp',
  path: '/aajp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aajp': typeof AajpRoute
  '/auth': typeof AuthRoute
  '/leave': typeof LeaveRoute
  '/map': typeof MapRoute
  '/memories': typeof MemoriesRoute
  '/moderation': typeof ModerationRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aajp': typeof AajpRoute
  '/auth': typeof AuthRoute
  '/leave': typeof LeaveRoute
  '/map': typeof MapRoute
  '/memories': typeof MemoriesRoute
  '/moderation': typeof ModerationRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aajp': typeof AajpRoute
  '/auth': typeof AuthRoute
  '/leave': typeof LeaveRoute
  '/map': typeof MapRoute
  '/memories': typeof MemoriesRoute
  '/moderation': typeof ModerationRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aajp'
    | '/auth'
    | '/leave'
    | '/map'
    | '/memories'
    | '/moderation'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aajp'
    | '/auth'
    | '/leave'
    | '/map'
    | '/memories'
    | '/moderation'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/aajp'
    | '/auth'
    | '/leave'
    | '/map'
    | '/memories'
    | '/moderation'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AajpRoute: typeof AajpRoute
  AuthRoute: typeof AuthRoute
  LeaveRoute: typeof LeaveRoute
  MapRoute: typeof MapRoute
  MemoriesRoute: typeof MemoriesRoute
  ModerationRoute: typeof ModerationRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aajp': {
      id: '/aajp'
      path: '/aajp'
      fullPath: '/aajp'
      preLoaderRoute: typeof AajpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AajpRoute: AajpRoute,
  AuthRoute: AuthRoute,
  LeaveRoute: LeaveRoute,
  MapRoute: MapRoute,
  MemoriesRoute: MemoriesRoute,
  ModerationRoute: ModerationRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
